# For more information: https://laravel.com/docs/sail
version: "3.5"
services:
  wp:
    container_name: wp_host
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${HTTP_PORT:-80}:80 # change HOST if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_DATABASE}"
      WORDPRESS_DB_USER: "${DB_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - wp_network
  cli:
    container_name: wp_cli
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_DATABASE}"
      WORDPRESS_DB_USER: "${DB_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - mysql
      - wp
    networks:
      - wp_network
  mysql:
    container_name: "wp_mysql"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"  
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - "mysql_volume:/var/lib/mysql"
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - "wp_network"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10
  phpmyadmin:
    container_name: "wp_phpmyadmin"
    image: phpmyadmin
    ports:
      - "${FORWARD_PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    depends_on:
      - "mysql"
    networks:
      - "wp_network"
networks:
  wp_network:
    driver: bridge
volumes:
  mysql_volume:
    driver: local
